openapi: 3.0.0

info:
  title: Log analytics API
  description: Log stream analysis API
  contact:
    email: innov.petercortez@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: 1.0.0

tags:
  - name: analytics
    description: Analytics functions

paths:
  /logs/count:
    get:
      tags:
        - analytics
      description: Searches log entries and provides aggregated count of matches
      parameters:
        - name: serviceNames
          in: query
          description: Array of service names
          schema:
            type: array
            items:
              $ref: "./openapi/fields/log_entry.yml#/properties/service_name"
        - name: startDate
          in: query
          description: start date
          schema:
            $ref: "./openapi/fields/log_entry.yml#/properties/logged_at"
        - name: endDate
          in: query
          description: end date
          schema:
            $ref: "./openapi/fields/log_entry.yml#/properties/logged_at"
        - name: statusCode
          in: query
          description: filter on request status code
          schema:
            $ref: "./openapi/fields/log_entry.yml#/properties/http_status_code"
      responses:
        '200':
          description: count of matching results
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      count:
                        type: integer
                        example: 100
        '422':
          description: bad input parameter
          content:
            application/json:
              schema:
                $ref: "./openapi/responses/unprocessable-entity.yml"
  /logs:
    delete:
      tags:
        - analytics
      description: Delete all log entries in the database
      responses:
        '204':
          $ref: "./openapi/responses/no-content.yml"
