<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240619081703 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('
            CREATE TABLE log_entry
            (
                id                    INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                service_name          VARCHAR(32)                          NOT NULL,
                logged_at             TIMESTAMP(0) WITHOUT TIME ZONE       NOT NULL,
                http_request_method   VARCHAR(255)                         NOT NULL,
                http_request_target   TEXT                                 NOT NULL,
                http_protocol_version NUMERIC(2, 1)                        NOT NULL,
                http_status_code      SMALLINT                             NOT NULL,
                PRIMARY KEY (id)
            )
        ');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('DROP TABLE log_entry');
    }
}
